version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "producer-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m502eks8szzi"
s3_prefix = "producer-lambda"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=728696026803.dkr.ecr.us-east-2.amazonaws.com/wikiserve"]
